// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package dbgen

import (
	"context"
	"time"
)

const acceptInvitation = `-- name: AcceptInvitation :execrows
UPDATE invitations
SET accepted_at = now()
WHERE organization_id = $1 AND id = $2
  AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()
`

type AcceptInvitationParams struct {
	OrganizationID int64
	ID             int64
}

// Returns 0 rows when the invitation is no longer pending (accepted, revoked, or expired).
func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptInvitation, arg.OrganizationID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createInvitation = `-- name: CreateInvitation :one

INSERT INTO invitations (organization_id, email, role, invited_by_user_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, email, role, invited_by_user_id, created_at, expires_at, accepted_at, revoked_at
`

type CreateInvitationParams struct {
	OrganizationID  int64
	Email           string
	Role            OrgRole
	InvitedByUserID *int64
	ExpiresAt       time.Time
}

// Inside one nursery (run through db.InTenant) --
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.InvitedByUserID,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
	)
	return i, err
}

const extendInvitation = `-- name: ExtendInvitation :one
UPDATE invitations
SET expires_at = $1
WHERE organization_id = $2 AND id = $3
RETURNING id, organization_id, email, role, invited_by_user_id, created_at, expires_at, accepted_at, revoked_at
`

type ExtendInvitationParams struct {
	ExpiresAt      time.Time
	OrganizationID int64
	ID             int64
}

func (q *Queries) ExtendInvitation(ctx context.Context, arg ExtendInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, extendInvitation, arg.ExpiresAt, arg.OrganizationID, arg.ID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getInvitationForEmail = `-- name: GetInvitationForEmail :one
SELECT i.id, i.organization_id, i.role, o.status AS organization_status
FROM invitations i
JOIN organizations o ON o.id = i.organization_id
WHERE i.id = $1 AND i.email = $2
`

type GetInvitationForEmailParams struct {
	ID    int64
	Email string
}

type GetInvitationForEmailRow struct {
	ID                 int64
	OrganizationID     int64
	Role               OrgRole
	OrganizationStatus OrganizationStatus
}

func (q *Queries) GetInvitationForEmail(ctx context.Context, arg GetInvitationForEmailParams) (GetInvitationForEmailRow, error) {
	row := q.db.QueryRow(ctx, getInvitationForEmail, arg.ID, arg.Email)
	var i GetInvitationForEmailRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Role,
		&i.OrganizationStatus,
	)
	return i, err
}

const getOpenInvitation = `-- name: GetOpenInvitation :one
SELECT id, organization_id, email, role, invited_by_user_id, created_at, expires_at, accepted_at, revoked_at FROM invitations
WHERE organization_id = $1 AND id = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type GetOpenInvitationParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) GetOpenInvitation(ctx context.Context, arg GetOpenInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, getOpenInvitation, arg.OrganizationID, arg.ID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getOpenInvitationByEmail = `-- name: GetOpenInvitationByEmail :one
SELECT id, organization_id, email, role, invited_by_user_id, created_at, expires_at, accepted_at, revoked_at FROM invitations
WHERE organization_id = $1 AND email = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type GetOpenInvitationByEmailParams struct {
	OrganizationID int64
	Email          string
}

func (q *Queries) GetOpenInvitationByEmail(ctx context.Context, arg GetOpenInvitationByEmailParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, getOpenInvitationByEmail, arg.OrganizationID, arg.Email)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
	)
	return i, err
}

const isMemberByEmail = `-- name: IsMemberByEmail :one
SELECT EXISTS (
    SELECT 1 FROM memberships m
    JOIN users u ON u.id = m.user_id
    WHERE m.organization_id = $1 AND u.email = $2
)
`

type IsMemberByEmailParams struct {
	OrganizationID int64
	Email          string
}

func (q *Queries) IsMemberByEmail(ctx context.Context, arg IsMemberByEmailParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMemberByEmail, arg.OrganizationID, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const joinOrganization = `-- name: JoinOrganization :exec
INSERT INTO memberships (organization_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (organization_id, user_id) DO NOTHING
`

type JoinOrganizationParams struct {
	OrganizationID int64
	UserID         int64
	Role           OrgRole
}

// Adds the membership; someone who is already a member keeps their current role.
func (q *Queries) JoinOrganization(ctx context.Context, arg JoinOrganizationParams) error {
	_, err := q.db.Exec(ctx, joinOrganization, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}

const listOpenInvitations = `-- name: ListOpenInvitations :many
SELECT id, organization_id, email, role, invited_by_user_id, created_at, expires_at, accepted_at, revoked_at FROM invitations
WHERE organization_id = $1 AND accepted_at IS NULL AND revoked_at IS NULL
ORDER BY created_at DESC
`

// Not yet accepted or revoked (expired ones included, so they can be resent).
func (q *Queries) ListOpenInvitations(ctx context.Context, organizationID int64) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listOpenInvitations, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.InvitedByUserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsForEmail = `-- name: ListPendingInvitationsForEmail :many

SELECT i.id, i.organization_id, o.name AS organization_name, i.role, i.expires_at
FROM invitations i
JOIN organizations o ON o.id = i.organization_id
WHERE i.email = $1 AND i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at > now()
  AND o.status = 'active'
ORDER BY i.created_at
`

type ListPendingInvitationsForEmailRow struct {
	ID               int64
	OrganizationID   int64
	OrganizationName string
	Role             OrgRole
	ExpiresAt        time.Time
}

// Account level: invitations addressed to one person, across nurseries --
func (q *Queries) ListPendingInvitationsForEmail(ctx context.Context, email string) ([]ListPendingInvitationsForEmailRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsForEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitationsForEmailRow{}
	for rows.Next() {
		var i ListPendingInvitationsForEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.Role,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :exec
UPDATE invitations
SET revoked_at = now()
WHERE organization_id = $1 AND id = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeInvitationParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) error {
	_, err := q.db.Exec(ctx, revokeInvitation, arg.OrganizationID, arg.ID)
	return err
}
