// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package dbgen

import (
	"context"
	"time"
)

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM memberships
WHERE organization_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, organizationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (organization_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, organization_id, user_id, role, created_at
`

type CreateMembershipParams struct {
	OrganizationID int64
	UserID         int64
	Role           OrgRole
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.OrganizationID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM memberships
WHERE organization_id = $1 AND id = $2
`

type DeleteMemberParams struct {
	OrganizationID int64
	ID             int64
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.OrganizationID, arg.ID)
	return err
}

const getAccess = `-- name: GetAccess :one
SELECT m.id AS membership_id, m.role, o.status AS organization_status
FROM memberships m
JOIN organizations o ON o.id = m.organization_id
WHERE m.organization_id = $1 AND m.user_id = $2
`

type GetAccessParams struct {
	OrganizationID int64
	UserID         int64
}

type GetAccessRow struct {
	MembershipID       int64
	Role               OrgRole
	OrganizationStatus OrganizationStatus
}

// The user's role in an organization, and whether the organization is active.
func (q *Queries) GetAccess(ctx context.Context, arg GetAccessParams) (GetAccessRow, error) {
	row := q.db.QueryRow(ctx, getAccess, arg.OrganizationID, arg.UserID)
	var i GetAccessRow
	err := row.Scan(&i.MembershipID, &i.Role, &i.OrganizationStatus)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT m.id, m.user_id, u.email, u.display_name, m.role, m.created_at
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.organization_id = $1 AND m.id = $2
`

type GetMemberParams struct {
	OrganizationID int64
	ID             int64
}

type GetMemberRow struct {
	ID          int64
	UserID      int64
	Email       string
	DisplayName *string
	Role        OrgRole
	CreatedAt   time.Time
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error) {
	row := q.db.QueryRow(ctx, getMember, arg.OrganizationID, arg.ID)
	var i GetMemberRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT m.id, m.user_id, u.email, u.display_name, m.role, m.created_at
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.organization_id = $1
ORDER BY m.role, u.email
`

type ListMembersRow struct {
	ID          int64
	UserID      int64
	Email       string
	DisplayName *string
	Role        OrgRole
	CreatedAt   time.Time
}

// Owners first (enum order: owner, admin, staff, viewer), then by email.
func (q *Queries) ListMembers(ctx context.Context, organizationID int64) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT o.id AS organization_id, o.name AS organization_name, o.slug, o.status, m.role
FROM memberships m
JOIN organizations o ON o.id = m.organization_id
WHERE m.user_id = $1
ORDER BY o.name
`

type ListMembershipsForUserRow struct {
	OrganizationID   int64
	OrganizationName string
	Slug             string
	Status           OrganizationStatus
	Role             OrgRole
}

func (q *Queries) ListMembershipsForUser(ctx context.Context, userID int64) ([]ListMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForUserRow{}
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.OrganizationName,
			&i.Slug,
			&i.Status,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE memberships
SET role = $1
WHERE organization_id = $2 AND id = $3
`

type UpdateMemberRoleParams struct {
	Role           OrgRole
	OrganizationID int64
	ID             int64
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.Role, arg.OrganizationID, arg.ID)
	return err
}
