// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package dbgen

import (
	"context"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug, time_zone)
VALUES ($1, $2, $3)
RETURNING id, name, slug, time_zone, status, created_at
`

type CreateOrganizationParams struct {
	Name     string
	Slug     string
	TimeZone string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug, arg.TimeZone)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.TimeZone,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, time_zone, status, created_at FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.TimeZone,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const lockOrganization = `-- name: LockOrganization :exec
SELECT 1 FROM organizations
WHERE id = $1
FOR UPDATE
`

// Holds the organization's row until the transaction ends, so changes to its members run one at a time.
func (q *Queries) LockOrganization(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, lockOrganization, id)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name      = COALESCE($1, name),
    time_zone = COALESCE($2, time_zone)
WHERE id = $3
RETURNING id, name, slug, time_zone, status, created_at
`

type UpdateOrganizationParams struct {
	Name     *string
	TimeZone *string
	ID       int64
}

// Changes only the fields that are given (NULL keeps the current value).
func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.Name, arg.TimeZone, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.TimeZone,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
