// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package dbgen

import (
	"context"
	"time"
)

const getOrganizationWithMemberCount = `-- name: GetOrganizationWithMemberCount :one
SELECT o.id, o.name, o.slug, o.time_zone, o.status, o.created_at,
       (SELECT count(*) FROM memberships m WHERE m.organization_id = o.id) AS member_count
FROM organizations o
WHERE o.id = $1
`

type GetOrganizationWithMemberCountRow struct {
	ID          int64
	Name        string
	Slug        string
	TimeZone    string
	Status      OrganizationStatus
	CreatedAt   time.Time
	MemberCount int64
}

func (q *Queries) GetOrganizationWithMemberCount(ctx context.Context, id int64) (GetOrganizationWithMemberCountRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationWithMemberCount, id)
	var i GetOrganizationWithMemberCountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.TimeZone,
		&i.Status,
		&i.CreatedAt,
		&i.MemberCount,
	)
	return i, err
}

const listMembershipsForUsers = `-- name: ListMembershipsForUsers :many
SELECT m.user_id, o.id AS organization_id, o.name AS organization_name, m.role
FROM memberships m
JOIN organizations o ON o.id = m.organization_id
WHERE m.user_id = ANY($1::bigint[])
ORDER BY o.name
`

type ListMembershipsForUsersRow struct {
	UserID           int64
	OrganizationID   int64
	OrganizationName string
	Role             OrgRole
}

func (q *Queries) ListMembershipsForUsers(ctx context.Context, userIds []int64) ([]ListMembershipsForUsersRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUsers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForUsersRow{}
	for rows.Next() {
		var i ListMembershipsForUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsWithMemberCounts = `-- name: ListOrganizationsWithMemberCounts :many

SELECT o.id, o.name, o.slug, o.time_zone, o.status, o.created_at,
       (SELECT count(*) FROM memberships m WHERE m.organization_id = o.id) AS member_count
FROM organizations o
ORDER BY o.name
`

type ListOrganizationsWithMemberCountsRow struct {
	ID          int64
	Name        string
	Slug        string
	TimeZone    string
	Status      OrganizationStatus
	CreatedAt   time.Time
	MemberCount int64
}

// Platform admin, across nurseries (account data only: organizations, users, memberships) --
func (q *Queries) ListOrganizationsWithMemberCounts(ctx context.Context) ([]ListOrganizationsWithMemberCountsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsWithMemberCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsWithMemberCountsRow{}
	for rows.Next() {
		var i ListOrganizationsWithMemberCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.TimeZone,
			&i.Status,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, external_id, email, display_name, created_at FROM users
WHERE $1::text = '' OR strpos(email, $1::text) > 0
ORDER BY created_at DESC
LIMIT 50
`

// Newest first; an empty term matches everyone.
func (q *Queries) SearchUsers(ctx context.Context, term string) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, term)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganizationAccount = `-- name: UpdateOrganizationAccount :exec
UPDATE organizations
SET name   = COALESCE($1, name),
    status = COALESCE($2::organization_status, status)
WHERE id = $3
`

type UpdateOrganizationAccountParams struct {
	Name   *string
	Status *OrganizationStatus
	ID     int64
}

// Name and status (suspend or reactivate); NULL keeps the current value. Nurseries can't change status.
func (q *Queries) UpdateOrganizationAccount(ctx context.Context, arg UpdateOrganizationAccountParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationAccount, arg.Name, arg.Status, arg.ID)
	return err
}
