// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
)

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (external_id, email, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (external_id) DO UPDATE
SET email        = EXCLUDED.email,
    display_name = COALESCE(EXCLUDED.display_name, users.display_name)
RETURNING id, external_id, email, display_name, created_at
`

type UpsertUserParams struct {
	ExternalID  string
	Email       string
	DisplayName *string
}

// Creates the user on first sign-in, or refreshes their email and name from the session token.
// A missing name keeps the one already saved.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ExternalID, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}
